### ISSUE TITLE
Feature: Syntax Highlighting for Gobra

### ISSUE THREAD

**Issue by gottschali** [viperproject/gobra-book#7]
Provide proper syntax highlighting in the ace editor for gobra specification.
At least it should
- highlight gobra keywords like `pure`, `requires`
- highlight gobra operators like `==>`

It shall work in both `go` and `gobra` code blocks.
This means lines starting with  `//@` must not treated as comments as well as the inline/multiline variant `/*@ ... @*/`

**Comment by jcp19** [comment]
done in PR #5
